# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-6813d122-955f-468a-8c9f-c3cea92c6f94";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-6813d122-955f-468a-8c9f-c3cea92c6f94".device = "/dev/disk/by-uuid/6813d122-955f-468a-8c9f-c3cea92c6f94";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/EA2A-ECD0";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  hardware.bluetooth.enable = true;
  hardware.enableAllFirmware = true;
  
  hardware.wirelessRegulatoryDatabase = true;
  boot.extraModprobeConfig = ''
    options cfg80211 ieee80211_regdom="US"
  '';

  networking.networkmanager.wifi.powersave = false;  
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
